# Generated by Django 4.2.11 on 2024-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=200),
        ),
    ]
